### ISSUE TITLE
Can't get tag16h5 to work

### ISSUE THREAD

**Issue by kasperschnack** [MomsFriendlyRobotCompany/moms_apriltag#1]
Hi Kevin.

Thank you for making this 🙏. And I agree - there seemed to be no easy way of generating these 🤷
I Tried different shapes and sizes for tag16h5 - but kept getting 

python -m experiments.gen_apriltags                                                   [22/06/21|12:30:05]
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/kasperschnack/Projects/legofun/sortbot/experiments/gen_apriltags.py", line 11, in <module>
    tgt = apt.board(shape, family)
  File "/usr/local/lib/python3.9/site-packages/moms_apriltag/target.py", line 88, in board
    check_size(r, len(tag16h5.codes))
  File "/usr/local/lib/python3.9/site-packages/moms_apriltag/target.py", line 61, in check_size
    raise Exception(f"family board size exceeded: {r} != {size}")
Exception: family board size exceeded: 30 != 30

Any idea what could be the issue?

**Comment by walchko** [comment]
oh, tag16h5 is a much smaller family of tags compared to the example. ok, good feedback, my error message isn't the best. Change the board size to a smaller size like 5x5 (or 25 different tags) or something that generates no more than 29 tags in total.
